### ISSUE TITLE
The webpage has to be refreshed for the time to be recalculated again

### ISSUE THREAD

**Issue by Ishannaik** [edenizk/udemyRemainingTimerExtention#7]
I downloaded the extension from the chrome webstore and noticed that the webpage has to be refreshed for the time to be recalculated again, not sure if its a bug or an intended feature

**Comment by edenizk** [comment]
Hi, 

thank you for taking your time and giving a feedback. 
It was an bug, due to element attribute not updating after the state changes in react side 🙂
I've added a fix, I will submit a update to extension store (usually it takes 1-2 days)

if anything else don't hesitate to hit me 🙂
have a nice weekend 🤚
